#George Floyd Library Data Aquisition and Training 

In [9]:
#iterate through images and find ppl faces 
import numpy as np
import cv2
import matplotlib.pyplot as plt
from time import sleep
from shutil import copyfile
#Config the pipeline and get the face location data
face_cascade = cv2.CascadeClassifier('haarcascade_frontalface_default.xml')
import os
count = 0
facepics = []
directory = r'./challenge2018'
for filename in os.listdir(directory):
    if filename.endswith(".jpg") or filename.endswith(".png"):
        img = cv2.imread(os.path.join(directory, filename))
        gray = cv2.cvtColor(img, cv2.COLOR_BGR2GRAY)
        faces = face_cascade.detectMultiScale(gray, 1.3, 5)
        if len(faces):
          count = count + 1
          print(faces)
          print(os.path.join(directory, filename))
          facepics.append(os.path.join(directory, filename))
          copyfile(os.path.join(directory, filename), "./trainingdata/" + filename)
        if count == 1000:
          break
        #sleep(1)
    else:
        continue
#img = cv2.imread(allfiles[0])
#gray = cv2.cvtColor(img, cv2.COLOR_BGR2GRAY)
#faces = face_cascade.detectMultiScale(img, 1.3, 5)


[[288  81  64  64]
 [677  84  77  77]
 [181  95  64  64]
 [436 278  57  57]]
./challenge2018/ba4d8a88219945da.jpg
[[152 289 228 228]]
./challenge2018/8f728efe6bb4cb21.jpg
[[403  39 126 126]]
./challenge2018/b5af334e56ccbc13.jpg
[[776 211  53  53]]
./challenge2018/526e297e347ba6aa.jpg
[[727 192  80  80]
 [727 179 116 116]]
./challenge2018/28d2463ad1cea879.jpg
[[900 148  72  72]
 [812 292  69  69]
 [182 432  69  69]
 [541 432  69  69]
 [900 432  69  69]]
./challenge2018/740bc7f7503b6a4a.jpg
[[663 125  82  82]
 [518 143  61  61]]
./challenge2018/a4a0cf7d1901b3af.jpg
[[ 82  44 108 108]]
./challenge2018/f73e6410ce05dae8.jpg
[[507 653  58  58]]
./challenge2018/0dd678c1eec41d62.jpg
[[292 111  71  71]
 [434 141  61  61]
 [756 153  64  64]
 [185 163  70  70]
 [632 184  64  64]
 [465 537  73  73]]
./challenge2018/3e0b613a55784a2f.jpg
[[270 349  66  66]]
./challenge2018/d3a91c5c3ce8482a.jpg
[[540 136 127 127]
 [604 155  88  88]
 [385 203 117 117]]
./challenge2018/23cca606d6ab2a39.jpg
[[841 166  5

In [10]:
print(len(facepics))

1000


In [0]:
#iterate through and find bodies 
!pip install --upgrade openpifpaf==0.11.2
%matplotlib inline

import io
import numpy as np
import openpifpaf
import PIL
import requests
import torch

# device = torch.device('cpu')
device = torch.device('cuda')  # if cuda is available

print(openpifpaf.__version__)
print(torch.__version__)
image_response = requests.get('https://raw.githubusercontent.com/vita-epfl/openpifpaf/master/docs/coco/000000081988.jpg')
pil_im = PIL.Image.open(io.BytesIO(image_response.content)).convert('RGB')
im = np.asarray(pil_im)

with openpifpaf.show.image_canvas(im) as ax:
  pass

In [0]:
!wget https://datasets.appen.com/appen_datasets/open-images/test_challenge.zip && unzip test_challenge.zip